THIS IS MY FIRST SENTENCE.
ADDING A SECOND LINE IN THIS FILE
ADDING THIRD SENTENCE AFTER ADDING THE FILE TO GIT
ADDING THE FOURTH LINE TO VERIFY THE GIT LOGS
ADDING A LINE TO CHECK GIT REVERT
NEW GIT REVERT SENTENSE
